name: 'Hello World'
description: 'Greet someone and record time'
inputs:
  who-to-greet: #id for input
    description: 'Who to Greet'
    required: true
    default: 'World'
  
  outputs:
    time: #id for input
      description: 'The time we greeted you!'
    
  runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
      - ${{ inputs.who-to-greet }}
      